grpc:
  server:
    addr: "127.0.0.1:50051"
    name: testServer
    port: 50051
    exit-delay: 1s
etcd:
  endpoints:
    - "127.0.0.1:2379"

mysql:
  url: 127.0.0.1:3306
  username: root
  password: root
  database: grpc_demo
